### ISSUE TITLE
Améliorer les partages réseaux avec une image

### ISSUE THREAD

**Issue by doriansimeha** [deputedelahonte/deputesdelahonte.site#1]
Dans les méta : 

<meta property="og:image" content="Un.e_député.e_de_a_honte_aléatoire_ou_une_mozaïque_de_nos_député.e.s_de_la_honte.jpeg" />

**Comment by doriansimeha** [comment]
Hop!

![trombinocopedelahonte](https://user-images.githubusercontent.com/39616961/100528477-9018a600-31dd-11eb-8400-a5830d586306.jpg)

**Comment by ldoguin** [comment]
Merci @doriansimeha, c'est en ligne :)
